import Image from 'next/image';
import {Retry} from './retry';
import {SupportLink as Link} from './link';
import type {SupportEntry,SupportKind} from '@/lib/support/core';
import {entryHref,safeBack} from '@/lib/support/core';
import s from './support.module.css';
export function SupportHero({title,description,home=false}:{title:string;description:string;home?:boolean}){return <header className={s.hero}><div className={s.container}><nav aria-label="현재 위치" className={s.crumb}><Link href="/">홈</Link><span>/</span>{home?<span aria-current="page">고객지원</span>:<><Link href="/support/">고객지원</Link><span>/</span><span aria-current="page">{title}</span></>}</nav><p className={s.eyebrow}>CUSTOMER SUPPORT</p><h1>{home?<>마케팅과 교육,<br/>필요한 정보를 한곳에서.</>:title}</h1><p style={{whiteSpace:'pre-line'}}>{description}</p></div></header>}
export function Consultation(){return <section className={s.cta}><div><h2>우리 브랜드에는 무엇이 필요할까요?</h2><p>가맹문의, 가맹점 매출, 마케팅 운영, 교육 중<br/>지금 해결하고 싶은 고민을 남겨주세요.</p></div><Link className={s.button} href="/support/inquiry/">마케팅·교육 문의하기</Link></section>}
export function Empty({state,kind}:{state:string;kind:SupportKind}){return state==='ready'?<p className={s.empty}>{kind==='notices'?'등록된 공지사항이 없습니다.':kind==='resources'?'현재 공개된 자료가 없습니다.':'등록된 자주 묻는 질문이 없습니다.'}</p>:<div role="alert" className={s.error}><p>현재 목록을 불러올 수 없습니다. 잠시 후 다시 확인해 주세요.</p><Retry/><Link href="/support/inquiry/">전화·이메일로 문의하기 →</Link></div>}
export function Notices({entries,query={}}:{entries:SupportEntry[];query?:Record<string,string|undefined>}){const back=new URLSearchParams(query as Record<string,string>).toString();return <ul className={s.rows}>{entries.map(e=><li key={e.id}><Link href={entryHref(e)+(back?'?'+back:'')}>{e.thumbnail&&<Image width={100} height={80} className={s.noticeThumb} src={e.thumbnail} alt="" loading="lazy"/>}<strong>{e.pinned&&<span className={s.badge}>공지</span>}{e.title}</strong><time className={s.date} dateTime={e.publishedAt}>{e.publishedAt.slice(0,10)}</time></Link></li>)}</ul>}
export function ResourceCards({entries,query={},heading=3}:{entries:SupportEntry[];query?:Record<string,string|undefined>;heading?:2|3}){const Heading=heading===2?'h2':'h3';const params=new URLSearchParams(Object.entries(query).filter((p):p is [string,string]=>!!p[1])).toString();return <div className={s.resources}>{entries.map(e=><Link className={s.resource} key={e.id} href={entryHref(e)+(params?'?'+params:'')}><span className={s.fileIcon}>{[...new Set(e.files.map(f=>f.name.split('.').pop()?.toUpperCase()))].join(' · ')}</span><small>{e.category}</small><Heading>{e.title}</Heading><p>{e.summary}</p><b>자료 확인하기 →</b></Link>)}</div>}
export function Search({kind,q,category}:{kind:SupportKind;q:string;category:string}){return <form className={s.search} action={`/support/${kind}/`} method="get"><label htmlFor="support-search">{kind==='faq'?'질문·답변 검색':'제목·본문 검색'}<input id="support-search" type="search" name="q" defaultValue={q} maxLength={100} placeholder="검색어를 입력하세요"/></label>{category!=='전체'&&<input type="hidden" name="category" value={category}/>}<button className={s.button} type="submit">검색</button></form>}
export function Filters({kind,categories,q,selected}:{kind:SupportKind;categories:string[];q:string;selected:string}){return <nav className={s.filters} aria-label="분류">{['전체',...categories].map(category=><Link key={category} href={safeBack(kind,{q,category:category==='전체'?undefined:category})} aria-current={selected===category?'page':undefined}>{category}</Link>)}</nav>}
export function Pager({kind,page,pages,q,category}:{kind:SupportKind;page:number;pages:number;q:string;category:string}){if(pages<2)return null;const choices=[...new Set([1,...Array.from({length:5},(_,i)=>page-2+i).filter(p=>p>=1&&p<=pages),pages])].sort((a,b)=>a-b);return <nav className={s.pager} aria-label="목록 페이지">{choices.map(p=><Link key={p} href={safeBack(kind,{q,category:category==='전체'?undefined:category,page:String(p)})} aria-label={`${p}페이지`} aria-current={p===page?'page':undefined}>{p}</Link>)}</nav>}
