import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ChartNoAxesCombined,Users,Search,Store,Video,Monitor,GraduationCap,Compass} from 'lucide-react';
import {cases,insights} from '@/data/content';
import {services} from '@/data/services';
import {HomeInquiry} from './home-inquiry';
import {metrics,process,work,challenges,solutions,differences,audiences,subjects} from './home-redesign-data';
import s from './home-redesign.module.css';

function Wrap({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`${s.wrap} ${className}`}>{children}</div>}
function Label({children}:{children:React.ReactNode}){return <p className={s.kicker}>{children}</p>}
function CTA({children,href='#inquiry',secondary=false}:{children:React.ReactNode;href?:string;secondary?:boolean}){return <Link className={secondary?s.secondary:s.primary} href={href}>{children}<ArrowRight size={17}/></Link>}
function Photo({file,alt,priority=false}:{file:string;alt:string;priority?:boolean}){return <Image src={`/images/${file}`} alt={alt} fill sizes="(max-width:768px) 100vw, 640px" priority={priority}/>}

export function Hero(){return <section className={s.hero}><div className={s.heroImage}><Photo file="home-franchise-photo.jpg" alt="회의·컨설팅 업무를 설명하는 참고 사진" priority/></div><Wrap><div className={s.heroCopy}><Label>FRANCHISE GROWTH MARKETING</Label><h1>프랜차이즈 마케팅,<br/>왜 <em>가맹문의</em>로<br/>이어지지 않을까요?</h1><p>광고비를 늘리는 것만으로는 브랜드가 성장하지 않습니다.<br/>{" "}염원컴퍼니는 본사 전략부터 가맹모집, 가맹점 매출까지<br/>{" "}프랜차이즈의 전체 성장 구조를 설계합니다.</p><div className={s.actions}><CTA>우리 브랜드 성장 진단받기</CTA><CTA href="#solutions" secondary>서비스와 성공사례 보기</CTA></div></div></Wrap></section>}
export function CompanyOverview(){return <section className={s.section}><Wrap className={s.twoCol}><div><Label>YUMONE COMPANY</Label><h2>프랜차이즈 현장을 아는 사람이<br/>브랜드의 성장 전략을 설계합니다.</h2><p className={s.body}>염원컴퍼니는 프랜차이즈 마케팅과 교육을 전문으로 합니다. 본사와 가맹점의 현장에서 쌓은 경험을 바탕으로 가맹문의, 브랜드 검색, 콘텐츠와 교육을 하나의 성장 구조로 연결합니다.</p><Link className={s.textLink} href="/about">염원컴퍼니 알아보기 <ArrowRight size={16}/></Link></div><dl className={s.metrics}>{metrics.map(([value,label])=><div key={value}><dt>{value}</dt><dd>{label}</dd></div>)}</dl></Wrap></section>}
export function GrowthProcess(){return <section className={`${s.section} ${s.warm}`}><Wrap><Label>YUMONE GROWTH SYSTEM</Label><h2>브랜드가 성장할 구조부터 설계합니다.</h2><p className={s.body}>브랜드의 문제를 진단하고 검색·AI 노출부터 콘텐츠와 광고, 본사·가맹점 교육까지 하나의 흐름으로 연결합니다.</p><ol className={s.process}>{process.map(([en,title,body],i)=><li key={en}><span className={s.circle}>{String(i+1).padStart(2,'0')}</span><small>{en}</small><h3>{title}</h3><p>{body}</p></li>)}</ol><div className={s.outcome}>지속 가능한 브랜드 성장</div><div className={s.sectionFoot}><p>진단에서 끝나지 않고, 실행 결과를 다시 분석해 다음 전략에 반영합니다.</p><CTA>우리 브랜드의 성장 구조 진단받기</CTA></div></Wrap></section>}
export function WorkMethod(){return <section className={s.section}><Wrap><Label>HOW WE WORK</Label><h2>전략만 제안하지 않습니다.<br/>실행되는 현장까지 함께합니다.</h2><p className={s.body}>전략회의와 매출 활성화부터 콘텐츠 제작, AI 검색 최적화, 실무 교육까지 브랜드 성장에 필요한 과정을 연결합니다.</p><div className={s.work}>{work.map(([title,body,file])=><article key={title}><div className={s.workPhoto}><Photo file={file} alt={`${title} 업무 참고 사진`}/></div><h3>{title}</h3><p>{body}</p></article>)}</div><p className={s.note}>위 사진은 업무 이해를 돕는 참고 사진입니다. 실제 프로젝트 현장 사진은 자료 확인 후 반영합니다.</p></Wrap></section>}
export function GrowthStructure(){return <section className={`${s.section} ${s.warm}`}><Wrap className={s.twoCol}><div><Label>WHY YUMONE</Label><h2>프랜차이즈의 성과는<br/>광고 밖에서 결정됩니다.</h2><p className={s.body}>가맹문의가 실제 상담과 계약으로 이어지고, 마케팅이 가맹점 매출과 연결되려면 브랜드 전략부터 본사 시스템과 현장 실행까지 함께 움직여야 합니다.</p><CTA>우리 브랜드 성장 구조 진단받기</CTA></div><ol className={s.timeline}>{[['브랜드 전략','브랜드의 경쟁력과 성장 방향을 정리합니다.'],['고객 발견','검색과 콘텐츠를 통해 브랜드가 발견되게 합니다.'],['상담·구매 전환','고객의 관심을 가맹문의와 매장 방문으로 연결합니다.'],['현장 실행','본사와 가맹점이 같은 방향으로 실행하도록 돕습니다.']].map(([title,body],i)=><li key={title}><span className={s.circle}>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></Wrap></section>}
export function ProblemSection(){return <section className={s.section}><Wrap className={s.twoCol}><div><Label>FRANCHISE GROWTH PROBLEMS</Label><h2>광고는 계속하는데,<br/>왜 가맹문의와 매출은 늘지 않을까요?</h2><p className={s.body}>마케팅이 채널마다 흩어져 있기 때문입니다.<br/>발견 → 관심 → 상담 → 방문으로 이어지는<br/>성장 구조가 필요한 것입니다.</p></div><div className={s.problems}>{challenges.map(([title,body],i)=><article key={title}><small>{String(i+1).padStart(2,'0')}</small><h3>{title}</h3><p>{body}</p></article>)}</div></Wrap></section>}
export function GrowthFunnel(){return <section className={`${s.section} ${s.warm}`}><Wrap><Label>CONNECTED GROWTH</Label><h2>발견부터 현장 실행까지,<br/>브랜드의 다음 행동을 연결합니다.</h2><div className={s.funnel}>{[['발견','검색·AI에서 브랜드를 만납니다.'],['관심','콘텐츠로 강점과 차이를 이해합니다.'],['상담','홈페이지에서 질문과 문의로 이어집니다.'],['현장 실행','방문·교육·운영으로 경험을 완성합니다.']].map(([title,body],i)=><div key={title}><small>0{i+1}</small><h3>{title}</h3><p>{body}</p>{i<3&&<ArrowRight aria-hidden="true" size={20}/>}</div>)}</div><Link className={s.textLink} href="/ai-search">검색과 AI에서 발견되는 구조 보기 <ArrowRight size={16}/></Link></Wrap></section>}
export function ServiceGrid(){const icons=[ChartNoAxesCombined,Users,Search,Store,Video,Monitor,GraduationCap,Compass];return <section className={`${s.section} ${s.warm}`} id="solutions"><Wrap><Label>WHAT WE DO</Label><h2>프랜차이즈 성장을 만드는<br/>8가지 실행 솔루션</h2><p className={s.body}>전략 수립부터 가맹모집, 매출 활성화, 콘텐츠와 교육까지 필요한 실행을 연결합니다.</p><div className={s.solutions}>{solutions.map(([title,body,href],i)=>{const Icon=icons[i];return <article key={title}><div className={s.cardTop}><small>0{i+1}</small><Icon size={21} aria-hidden="true"/></div><h3>{title}</h3><p>{body}</p><Link href={href} className={s.textLink}>{title} 보기 <ArrowRight size={16}/></Link></article>})}</div><Link className={s.textLink} href="#cases">실행 과정과 사례 함께 보기 <ArrowRight size={16}/></Link></Wrap></section>}
export function DifferenceSection(){return <><section className={s.redBanner}><Wrap><h2>모든 브랜드에<br/>같은 마케팅을 제안하지 않습니다.</h2><p>업종, 가맹점 수, 예산과 목표를 확인하고 지금 필요한 전략부터 제안합니다.</p><CTA>우리 브랜드 맞춤 전략 상담받기</CTA></Wrap></section><section className={s.section}><Wrap><Label>WHY YUMONE COMPANY</Label><h2>프랜차이즈를 경험한 사람이<br/>프랜차이즈 마케팅을 설계합니다.</h2><div className={s.differences}>{differences.map(([title,body],i)=><article key={title}><small>0{i+1}</small><h3>{title}</h3><p>{body}</p></article>)}</div></Wrap></section></>}
export function ExpertProfile(){return <section className={s.expert}><Wrap className={s.expertGrid}><figure><div className={s.expertImage}><Photo file="yeom-hyedan-profile2.png" alt="염혜단 염원컴퍼니 대표"/></div><figcaption>YUMONE COMPANY · FOUNDER</figcaption></figure><div className={s.expertCopy}><Label>FRANCHISE BUSINESS EXPERT</Label><h2>현장을 알기에<br/><em>실행 가능한 전략</em>을 만듭니다.</h2><p>20년간 프랜차이즈 본사에서 마케팅과 교육을 경험하고,<br/>{" "}수많은 본사와 가맹점의 현장을 직접 만났습니다.<br/>{" "}이론보다 실행, 광고보다 성장을 만드는 구조에 집중합니다.</p><div className={s.tags}>{['프랜차이즈 본사 실무','마케팅·교육·영업','본사·SV·점주 교육','AI 검색 최적화'].map(x=><span key={x}>{x}</span>)}</div><p className={s.expertName}>염혜단 대표 <span>염원컴퍼니</span></p><CTA href="/about#ceo">대표 전문성 자세히 보기</CTA></div></Wrap></section>}
export function CaseStudies(){return <section className={s.section} id="cases"><Wrap><Label>PROJECT RESULTS</Label><h2>실행 과정과<br/>확인된 결과로 보여드립니다.</h2><p className={s.note}>현재 사례는 구성 예시입니다. 실제 고객사와 확인된 성과는 검증 후 공개합니다.</p><div className={s.cases}>{cases.slice(0,2).map(c=><article key={c.slug}><small>{c.category} · 구성 예시</small><h3>{c.title}</h3><dl><dt>해결해야 할 문제</dt><dd>{c.problem}</dd><dt>실행 전략</dt><dd>{c.service} · 세부 실행 내용 확인 예정</dd><dt>확인된 결과</dt><dd>검증된 성과 자료 공개 준비 중</dd></dl><Link className={s.textLink} href={`/project/marketing/${c.slug}`}>사례 구성 보기 <ArrowRight size={16}/></Link></article>)}</div></Wrap></section>}
export function Insights(){return <section className={`${s.section} ${s.dark}`}><Wrap><Label>FRANCHISE CONTENT HUB</Label><h2>프랜차이즈 현장에서 필요한 내용을<br/>쉽고 실용적으로 전합니다.</h2><div className={s.insights}>{insights.slice(0,3).map(c=><Link href={`/insight/column/${c.slug}`} key={c.slug}><small>{c.category}</small><h3>{c.title}</h3><p>{c.summary}</p><span className={s.textLink}>READ MORE <ArrowRight size={16}/></span></Link>)}<article><small>VIDEO · DOWNLOAD</small><h3>영상 콘텐츠와 실무 자료</h3><p>공식 영상 채널과 다운로드 자료는 확인 후 연결합니다.</p><span className={s.note}>자료 준비 중</span></article></div></Wrap></section>}
export function EducationPrograms(){return <section className={s.section}><Wrap><Label>EDUCATION</Label><h2>알고 끝나는 교육이 아니라<br/>현장에서 실행되는 교육을 만듭니다.</h2><div className={s.education}><div><h3>교육 대상</h3><div className={s.tags}>{audiences.map(x=><span key={x}>{x}</span>)}</div></div><div><h3>교육 분야</h3><div className={s.tags}>{subjects.map(x=><span key={x}>{x}</span>)}</div></div></div><CTA href="/education">우리 회사에 맞는 교육 프로그램 보기</CTA></Wrap></section>}
export function FAQ(){const faq=services.flatMap(x=>x.faq);return <section className={s.section}><Wrap><Label>FAQ</Label><h2>자주 묻는 질문</h2><div className={s.faq}>{faq.map(x=><details key={x.q}><summary>{x.q}<span aria-hidden="true"/></summary><p>{x.a}</p></details>)}</div></Wrap></section>}
export function Contact(){return <section className={`${s.section} ${s.warm}`} id="inquiry"><Wrap><div className={s.contactTitle}><Label>START YOUR FRANCHISE GROWTH</Label><h2>우리 브랜드에 지금 필요한 마케팅,<br/>현재의 고민부터 이야기해 주세요.</h2></div><div className={s.twoCol}><div><h3>브랜드의 다음 성장을 함께 설계합니다.</h3><p className={s.body}>현재의 성장 단계와 목표를 바탕으로<br/>필요한 서비스와 실행 방향을 정리합니다.</p><ol className={s.contactSteps}><li>브랜드 현황과 과제 확인</li><li>필요한 전략과 서비스 정리</li><li>실행 범위와 진행 방향 협의</li></ol><Link href="/contact" className={s.textLink}>상담 안내 자세히 보기 <ArrowRight size={16}/></Link></div><HomeInquiry/></div></Wrap></section>}
export function HomeRedesign(){return <div className={s.page}><Hero/><CompanyOverview/><GrowthProcess/><WorkMethod/><GrowthStructure/><ProblemSection/><GrowthFunnel/><ServiceGrid/><DifferenceSection/><ExpertProfile/><CaseStudies/><Insights/><EducationPrograms/><FAQ/><Contact/></div>}
