import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ArrowDown,RotateCcw,Search,Target,Megaphone,GraduationCap,ChartNoAxesCombined,Video,Monitor,Workflow,Users,BookOpen,Award,Check,Phone,Mail,MessageCircle,Youtube,Newspaper} from 'lucide-react';
import {stats,educationResults} from '../content/stats';
import {clients} from '../content/clients';
import {cases} from '../content/cases';
import {KAKAO_URL,PRIMARY_CTA} from '../content/site';
import {HomeInquiry} from './home-inquiry';
import {HomeMotion,CountUp} from './home-motion';
import s from './home-v2.module.css';
const real='/images/real/';
const services=[
 ['프랜차이즈 마케팅 전략','지금 필요한 실행 순서를 설계합니다.','/franchise/diagnosis/',Target],
 ['가맹모집 마케팅','브랜드 발견을 가맹 상담으로 연결합니다.','/franchise/recruit/',Megaphone],
 ['SEO·AEO·GEO 마케팅','검색과 AI에서 브랜드를 만나게 합니다.','/ai-search/',Search],
 ['가맹점 매출 활성화','우리 동네 고객이 찾는 매장을 만듭니다.','/franchise/sales/',ChartNoAxesCombined],
 ['숏폼·홍보영상 제작','브랜드의 강점을 영상으로 전합니다.','/content/shortform/',Video],
 ['프랜차이즈 실무 교육','배운 내용을 현장 실행으로 옮깁니다.','/education/',GraduationCap],
 ['홈페이지·랜딩페이지','서비스 이해부터 상담까지 연결합니다.','/content/website/',Monitor],
 ['본사 시스템·업무 자동화','반복 업무를 연결해 운영을 정리합니다.','/education/ai/',Workflow],
] as const;
const steps=[{title:'진단',sub:'브랜드의 막힌 지점을 찾습니다.',icon:Target,tags:['브랜드 진단 리포트']},{title:'발견',sub:'검색과 AI에서 발견되게 합니다.',icon:Search,tags:['검색 노출 구조','공식 정보 정비']},{title:'전환',sub:'관심을 상담으로 연결합니다.',icon:Megaphone,tags:['콘텐츠·광고','상담 랜딩페이지']},{title:'실행',sub:'본사와 가맹점이 함께 실행합니다.',icon:GraduationCap,tags:['교육·운영 매뉴얼']}];
const photos=[['hero-lecture','프랜차이즈 SV 교육 현장'],['edu-discussion','SV 교육 · 분임토의'],['edu-roleplay','SV 교육 · 점주 응대 역할극'],['edu-presentation','팀 프로젝트 발표'],['edu-ai-practice','가맹점 AI 마케팅 실습']];
const faqs=[['진단은 어떻게 진행되나요?','브랜드 현황과 현재 운영 채널, 목표를 확인한 뒤 상담과 진단 진행 방법을 안내합니다.'],['가맹모집 마케팅만 의뢰할 수 있나요?','네. 필요한 범위만 우선 시작할 수 있으며, 가맹모집 마케팅만 별도로 진행할 수도 있습니다.'],['SEO·AEO·GEO는 무엇이 다른가요?','SEO는 검색 결과 노출, AEO·GEO는 AI가 브랜드를 이해하고 답변에 참고하도록 정보와 신뢰 근거를 정리하는 작업입니다.'],['교육은 누구를 대상으로 하나요?','프랜차이즈 본사 직원, 슈퍼바이저, 가맹점주와 소상공인을 대상으로 실무 중심의 맞춤 교육을 진행합니다.'],['예산이 작아도 시작할 수 있나요?','가능합니다. 우선순위가 높은 1~2개 채널부터 시작해 상황에 맞춰 단계적으로 확장합니다.'],['상담 전에 어떤 자료가 필요한가요?','현재 운영 채널과 브랜드 소개 자료가 있으면 도움이 됩니다. 자료가 없어도 상담 과정에서 함께 확인합니다.']];
function Label({children,en}:{children:React.ReactNode;en:string}){return <p className={s.label}>{children}<small>{en}</small></p>}
function CTA(){return <a className={s.primary} href="#contact">{PRIMARY_CTA}<ArrowRight size={20}/></a>}
export function RedesignedHome(){return <div className={s.home}><HomeMotion/>
<section data-home-section id="home-hero" className={s.hero}><div className={s.heroInner}><div className={s.heroCopy}><Label en="YUMONE COMPANY">프랜차이즈 성장 파트너</Label><h1>프랜차이즈 마케팅,<br/>왜 <em>가맹문의</em>로<br/>이어지지 않을까요?</h1><p>프랜차이즈 본사 20년 실무 경험으로<br className={s.desktopBreak}/> 검색·콘텐츠·광고·교육을 하나의 성장 흐름으로 연결합니다.</p><div className={s.actions}><CTA/><a className={s.heroSecondary} href="#services">서비스 살펴보기 <ArrowDown size={18}/></a></div></div><div className={s.heroPhoto}><Image src="/images/pdf-reference/hero-meeting.png" alt="회의 테이블에서 자료를 살펴보며 토의하는 사람들" width={1639} height={925} sizes="(max-width: 760px) 100vw, 65vw" priority/></div></div><div className={s.trust}><span><Award/>한국프랜차이즈산업협회 전문강사</span><span><BookOpen/>『장사의 기술』 저자</span><span><Check/>소상공인진흥공단 심사위원</span><span><Users/>누적 교육 수강생 {stats[3].value}명+</span></div></section>
<section data-home-section id="company" className={s.section}><div className={s.container}><div className={s.splitHeading}><div><Label en="OUR EXPERIENCE">숫자로 보는 염원컴퍼니</Label><h2>현장을 이해하는 경험, <br className={s.headingBreak}/>성장을 설계하는 힘.</h2></div><div><p>염원컴퍼니는 AEO·GEO 기반 AI 검색 마케팅 대행사이자 프랜차이즈 교육 전문 회사입니다. 브랜드의 검색 콘텐츠 전략과 제작·운영을 지원하고, 프랜차이즈 본사 직원·슈퍼바이저·가맹점주를 위한 현장 중심 실무 교육을 제공합니다.</p><Link className={s.textLink} href="/about/#difference">염원컴퍼니의 차별점 보기 <ArrowRight size={18}/></Link></div></div><div className={s.stats}>{stats.map(item=><article key={item.label} className={s.card}><strong><CountUp value={item.value} suffix={item.suffix}/></strong><h3>{item.label}</h3><small>{item.basis}</small></article>)}</div></div></section>
<section data-home-section id="problems" className={`${s.section} ${s.warm}`}><div className={s.container}><Label en="YOUR CHALLENGES">우리 브랜드의 고민</Label><h2>이런 고민,<br className={s.headingBreak}/>우리 브랜드 이야기인가요?</h2><div className={s.problems}>{[{icon:Megaphone,title:'광고비는 쓰는데 가맹문의가 늘지 않는다',text:'노출에서 상담까지 이어지는 연결이 필요합니다.'},{icon:Search,title:'네이버·AI 검색에서 찾기 어렵다',text:'검색과 AI가 참고할 브랜드 정보가 부족합니다.'},{icon:ChartNoAxesCombined,title:'본사 마케팅과 가맹점 매출이 따로 움직인다',text:'본사의 전략이 매장의 실행으로 이어져야 합니다.'},{icon:Users,title:'콘텐츠·마케팅이 담당자 개인에게 의존한다',text:'담당자가 바뀌어도 지속되는 운영 체계가 필요합니다.'}].map(({icon:Icon,title,text})=><article className={s.card} key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div><p className={s.conclusion}>채널이 부족한 게 아니라,<br className={s.mobileBreak}/> <strong>발견 → 관심 → 상담 → 매출</strong>로 이어지는 구조가 필요합니다.</p></div></section>
<section data-home-section id="growth" className={`${s.section} ${s.dark}`}><div className={s.container}><Label en="GROWTH SYSTEM">염원컴퍼니의 성장 구조</Label><h2>진단부터 현장 실행까지,<br className={s.headingBreak}/>하나의 흐름으로 연결합니다.</h2><ol className={s.flow}>{steps.map(({title,sub,icon:Icon,tags},i)=><li key={title}><span className={s.stepNum}>0{i+1}</span><Icon size={32}/><h3>{title}</h3><p>{sub}</p><div className={s.tags}>{tags.map(tag=><span key={tag}>{tag}</span>)}</div></li>)}</ol><p className={s.loop}><RotateCcw size={20}/> 실행 성과를 분석하고, 다음 진단과 전략에 반영합니다.</p><CTA/></div></section>
<section data-home-section id="services" className={s.section}><div className={s.container}><Label en="OUR SERVICES">서비스</Label><h2>브랜드에 필요한<br className={s.headingBreak}/>8가지 실행 솔루션</h2><div className={s.services}>{services.map(([title,desc,href,Icon],i)=><Link href={href} className={s.card} key={title}><div className={s.serviceTop}><span>0{i+1}</span>{[2,7].includes(i)&&<b>CORE</b>}<Icon size={28}/></div><h3>{title}</h3><p>{desc}</p><span className={s.more}>자세히 <ArrowRight size={17}/></span></Link>)}</div><p className={s.banner}>모든 브랜드에 같은 마케팅을 제안하지 않습니다. <strong>업종·규모·목표에 맞춰 우선순위를 정합니다.</strong></p></div></section>
<section data-home-section id="field" className={`${s.section} ${s.warm}`}><div className={s.container}><Label en="IN THE FIELD">현장에서 함께합니다</Label><h2>설명에서 끝나지 않고,<br className={s.headingBreak}/>함께 해보는 교육.</h2><div className={s.gallery}>{photos.map(([file,caption])=><figure key={file}><Image src={real+file+'.webp'} alt={caption} width={file==='hero-lecture'?1508:960} height={file==='hero-lecture'?864:file==='edu-discussion'?681:file==='edu-ai-practice'?649:720} sizes="(max-width: 760px) 100vw, 50vw"/><figcaption>{caption}</figcaption></figure>)}</div><div className={s.tags}>{['본사 직원','슈퍼바이저','가맹점주','소상공인','CS·점주 응대','AI 마케팅 실습'].map(t=><span key={t}>{t}</span>)}</div><div className={s.actions}><CTA/><Link className={s.textLink} href="/education/">교육 프로그램 자세히 보기 <ArrowRight size={18}/></Link></div></div></section>
<section data-home-section id="founder" className={s.section}><div className={s.container}><div className={s.founder}><div className={s.portrait}><Image src={real+'founder-profile.webp'} alt="염원컴퍼니 염혜단 대표" width={306} height={459} sizes="(max-width: 760px) 70vw, 330px"/></div><div><Label en="YEOM HYEDAN">대표 소개</Label><h2>“본사 사무실과 가맹점 매장,<br className={s.headingBreak}/>두 곳 모두에서 일해 봤습니다.”</h2><ul className={s.career}>{['(現) ㈜염원컴퍼니 대표이사','(前) 죠스푸드·바르다 김선생 브랜드 마케팅 총괄 임원','(前) 멕시카나치킨 마케팅·교육·영업 총괄 임원','한국프랜차이즈산업협회 전문강사','소상공인진흥공단 희망리턴패키지 심사위원','숭실대 중소기업대학원 경영학 석사'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul><div className={s.tags}>{['프랜차이즈 업계 최초 평사원 출신 여성 임원','FC 경영학 석사','20년 실무'].map(t=><span key={t}>{t}</span>)}</div><Link className={s.textLink} href="/about/#ceo">염혜단 대표 자세히 보기 <ArrowRight size={18}/></Link></div></div><div className={s.media}><a href="https://www.yes24.com/goods/detail/147562111" target="_blank" rel="noopener noreferrer" className={s.card}><Image src={real+'book-cover.webp'} alt="염혜단 저서 장사의 기술 표지" width={315} height={325} sizes="80px"/><div><small>BOOK</small><h3>『장사의 기술』</h3><p>도서 살펴보기 <ArrowRight size={16}/></p></div></a><a href="https://www.youtube.com/@프차언니/" target="_blank" rel="noopener noreferrer" className={s.card}><Youtube size={36}/><div><small>YOUTUBE</small><h3>프차언니</h3><p>현장의 이야기를 영상으로 <ArrowRight size={16}/></p></div></a><Link href="/insight/" className={s.card}><Newspaper size={36}/><div><small>BLOG</small><h3>실무 인사이트</h3><p>마케팅의 변화를 읽습니다 <ArrowRight size={16}/></p></div></Link></div></div></section>
<section data-home-section id="results" className={`${s.section} ${s.warm}`}><div className={s.container}><Label en="RESULTS & VOICES">결과와 후기</Label><h2>교육이 끝난 뒤에도,<br className={s.headingBreak}/>현장에서 쓰이는 배움.</h2><div className={s.resultTop}><Image src={real+'edu-ai-practice.webp'} alt="수강생이 직접 참여하는 가맹점 AI 마케팅 실습" width={960} height={649} sizes="(max-width: 760px) 100vw, 40vw"/><div className={s.resultNumbers}>{educationResults.map(x=><article key={x.label}><strong>{x.value}</strong><h3>{x.label}</h3>{x.basis&&<small>{x.basis}</small>}</article>)}<small>출처: 고용노동부·한국산업인력공단 재직자 훈련 운영 결과 보고서</small></div></div><div className={s.quotes}><blockquote className={s.card}>“강사님 강의가 너무 유익했고 그동안 들은 강의보다 <mark>재밌고 현실감 느껴졌습니다.</mark>”<cite>SV 가맹점 CS</cite></blockquote><blockquote className={s.card}>“지금까지 들은 교육 중 <mark>실무 활용도가 높다고 느껴지고,</mark> 강사님의 설명이 매우 좋았다.”<cite>가맹점 AI 마케팅</cite></blockquote><blockquote className={s.card}>“변화하는 AI 트렌드를 빠르게 반영한 강의로, <mark>최신 내용을 지속적으로 학습하기 위해 재수강</mark>”<cite>가맹점 AI 마케팅</cite></blockquote></div>{cases.length>0&&<div className={s.quotes}>{cases.map(c=><Link key={c.href} href={c.href} className={s.card}><h3>{c.title}</h3><p>{c.description}</p></Link>)}</div>}</div></section>
<section data-home-section id="clients" className={s.section}><div className={s.container}><Label en="OUR CLIENTS">함께한 고객사</Label><h2>다양한 현장에서,<br className={s.headingBreak}/>함께 성장하고 있습니다.</h2><ul className={s.logos}>{clients.filter(c=>c.visible&&!c.institution).map(c=><li key={c.name}><Image src={c.src} alt={c.name} width={c.width} height={c.height} sizes="(max-width: 760px) 25vw, 150px"/></li>)}</ul><h3 className={s.institutionTitle}>협력·교육 기관</h3><ul className={`${s.logos} ${s.institutions}`}>{clients.filter(c=>c.visible&&c.institution).map(c=><li key={c.name}><Image src={c.src} alt={c.name} width={c.width} height={c.height} sizes="(max-width: 760px) 25vw, 200px"/></li>)}</ul></div></section>
<section data-home-section id="contact" className={`${s.section} ${s.warm}`}><div className={`${s.container} ${s.contact}`}><div><Label en="LET’S TALK">자주 묻는 질문 · 상담 신청</Label><h2>우리 브랜드의 다음 성장,<br className={s.headingBreak}/>함께 이야기해 보세요.</h2><div className={s.faq}>{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div><div className={s.formPanel}><h3>우리 브랜드 무료 진단</h3><p className={s.formIntro}>1영업일 안에 연락드립니다 · 상담 무료</p><HomeInquiry/><div className={s.contactLinks}><a href="tel:0269496859"><Phone size={18}/>02-6949-6859</a><a href="mailto:yumone300@gmail.com"><Mail size={18}/>이메일</a>{KAKAO_URL&&<a href={KAKAO_URL} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>카카오톡</a>}</div></div></div></section>
</div>}
