import {HomeVisual} from '@/components/home-visual';
import layout from './home-content.module.css';
import {homeServices,homeExpertise,homeValues} from '@/data/home-content';
import styles from './home-top.module.css';
import {homeKpis} from '@/data/home-top';
import {Portrait} from '@/components/portrait';
import Link from 'next/link';
import {ArrowUpRight,Check,Building2,ChartNoAxesCombined,GraduationCap,ScanSearch,Target,Users,Compass,Trophy,Star} from 'lucide-react';
import {Container,Button,SectionTitle,Photo} from '@/components/ui';
import {education} from '@/data/education';
import {insights} from '@/data/content';
import {CaseGrid} from '@/components/case-grid';
import {metadata as makeMetadata} from '@/lib/seo';
export const metadata=makeMetadata('프랜차이즈 성장 파트너','프랜차이즈의 성장을 마케팅과 교육으로 설계합니다. 가맹 문의부터 AI 검색, 본사·SV·점주 교육까지 염원컴퍼니와 연결하세요.','/');
const icons=[Building2,ChartNoAxesCombined,GraduationCap,Compass];
export default function Home(){return <>
<section className={styles.hero}><Container className={styles.container}><div className={styles.copy}><p className={`eyebrow ${styles.eyebrow}`}>FRANCHISE MARKETING · EDUCATION · CONSULTING</p><h1><span>프랜차이즈 본사의 성장을</span><span><em>가맹모집부터 가맹점 매출까지</em></span><span>하나의 전략으로 연결합니다.</span></h1><p className={styles.description}>염원컴퍼니는 20년 현장 경험을 바탕으로<br/>{' '}프랜차이즈 마케팅, AI 검색 최적화, 본사·가맹점 교육을 통해<br/>{' '}브랜드의 지속 가능한 성장을 만드는 전문 파트너입니다.</p><div className={styles.actions}><Button href="/contact">우리 브랜드 성장 진단받기</Button><Button secondary href="/services">서비스 자세히 보기</Button></div><ul className={styles.services} aria-label="핵심 서비스">{[{icon:Target,label:"가맹점 모집 마케팅"},{icon:ChartNoAxesCombined,label:"가맹점 매출 활성화"},{icon:GraduationCap,label:"본사·SV·점주 교육"},{icon:ScanSearch,label:"SEO·AEO·GEO 최적화"}].map(({icon:Icon,label})=><li key={label}><Icon size={20} aria-hidden="true"/><strong>{label}</strong></li>)}</ul></div><div className={styles.visual}><div className={styles.portrait}><Portrait cutout/></div></div></Container></section>
<section className={styles.kpis} aria-label="주요 경험"><Container className={styles.container}>{homeKpis.map((item,index)=>{const Icon=[Trophy,Users,ChartNoAxesCombined,Star][index];return <div className={styles.kpi} key={item.label}><Icon aria-hidden="true"/><p><strong>{item.value}</strong><span>{item.label}</span></p></div>})}</Container></section>
<div className={layout.content}><section className="section"><Container><SectionTitle eyebrow="OUR SERVICE" title={'프랜차이즈의 시작부터 성장까지,\n염원컴퍼니가 함께합니다.'} href="/services"/><div className="service-grid">{homeServices.map((s,i)=>{const Icon=icons[i];return <Link className="service-card" key={s.slug} href={s.href}><Photo name={s.image} alt={`${s.short} 분야 참고 이미지`}/><div className="card-content"><span className="icon-red"><Icon size={22}/></span><span className="card-number">0{i+1}</span><h3>{s.short}</h3><p>{s.summary}</p><span className="red-link">자세히 보기 <ArrowUpRight size={16}/></span></div></Link>})}</div></Container></section>
<section className="section ai-section"><Container><div><p className="eyebrow">AI SEARCH MARKETING</p><h2>광고 클릭을 넘어,<br/>AI가 먼저 추천하는 브랜드로.</h2><p>고객과 예비 창업자는 이제 검색 결과뿐 아니라<br/>ChatGPT, Gemini, Perplexity 등 AI에게<br/>브랜드와 창업 정보를 묻습니다.</p><p>염원컴퍼니는 SEO·AEO·GEO를 기반으로<br/>브랜드가 AI에게 정확히 이해되고<br/>신뢰받는 선택지가 되는 구조를 만듭니다.</p><Button href="/contact?service=ai">AI 브랜드 추천 가능성 진단</Button></div><div className="search-framework"><span className="framework-title">BRAND DISCOVERY FRAMEWORK</span>{[{n:'SEO',label:'검색에서 발견되는 구조',detail:'Search Engine Optimization'},{n:'AEO',label:'질문에 답하는 구조',detail:'Answer Engine Optimization'},{n:'GEO',label:'AI가 이해하고 추천하는 구조',detail:'Generative Engine Optimization'}].map(s=><div key={s.n}><strong>{s.n}</strong><span>{s.label}<small>{s.detail}</small></span><ArrowUpRight size={24}/></div>)}<small>AI 답변과 추천 여부는 플랫폼·질문·시점에 따라 달라집니다.</small></div></Container></section>
<section className="section soft ceo-section"><Container><div className="ceo-placeholder"><Portrait src="/images/yeom-hyedan-profile2.png"/></div><div><p className="eyebrow">FRANCHISE EXPERT</p><h2>20년 프랜차이즈 현장에서<br/>성장의 답을 찾았습니다.</h2><p className={layout.ceoQuote}>“마케팅만 보는 것이 아니라<br/>본사와 가맹점이 함께 성장하는 구조를 봅니다.”</p><ul className={layout.expertise}>{homeExpertise.map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul><p className="ceo-name"><strong>염혜단 대표</strong></p><Button secondary href="/about#ceo">대표 소개 보기</Button></div></Container></section>
<section className="why-section"><Photo name="building" alt="유리 빌딩 참고 이미지"/><Container><p className="eyebrow">WHY YUMONE</p><h2>프랜차이즈를 아는 마케팅,<br/>현장을 아는 교육이 다릅니다.</h2><p>20년 프랜차이즈 현장 경험과 실무 노하우를 바탕으로<br/>브랜드의 성장과 가맹점의 성장을 연결합니다.</p><Button href="/about#why">염원컴퍼니가 특별한 이유</Button><div className="why-values">{homeValues.map((v,i)=>{const Icon=[Users,Target,GraduationCap,Compass][i];return <div key={v}><Icon size={30} strokeWidth={1.3}/><span>{v}</span></div>})}</div></Container></section>
<section className="section"><Container><SectionTitle eyebrow="SUCCESS STORY" title="결과로 증명하는 염원컴퍼니" description="브랜드의 과제부터 실행과 결과까지, 사례로 살펴보세요." href="/cases"/><CaseGrid franchiseLabel="프랜차이즈 시스템" home/></Container></section>

<section className="section soft"><Container><SectionTitle eyebrow="PRACTICAL EDUCATION" title={'현장에서 바로 쓰는\n프랜차이즈 실전 교육'} href="/education" linkText="교육 프로그램 보기"/><div className={layout.educationGrid}>{education.map((e,i)=><Link href={`/education/${e.slug}`} key={e.slug}><HomeVisual kind="education" index={i} label={e.title}/><div><span className="eyebrow">0{i+1}</span><h3>{e.slug==='headquarters'?'본사 직원 교육':e.title}</h3><p>{e.audience}</p><span className="red-link">교육 자세히 보기 <ArrowUpRight size={16}/></span></div></Link>)}</div><p className="content-note">실제 교육 현장 사진은 준비 중입니다. 위 영역은 교육 주제를 안내합니다.</p><Link className="text-link" href="/contact?service=education">기업·기관 출강 문의 <ArrowUpRight size={18}/></Link></Container></section>
<section className="section"><Container><SectionTitle eyebrow="NEWS & INSIGHT" title="프랜차이즈 성장 인사이트" href="/insights"/><Link className={layout.featured} href={`/insights/${insights[0].slug}`}><HomeVisual kind="insight" index={0} label="FRANCHISE"/><div><p className="eyebrow">FEATURED · {insights[0].category}</p><h3>{insights[0].title}</h3><p>{insights[0].summary}</p><time dateTime={insights[0].date}>{insights[0].date}</time><span className="red-link">인사이트 읽기 <ArrowUpRight size={18}/></span></div></Link><div className="insight-grid">{insights.slice(1).map((a,i)=><Link href={`/insights/${a.slug}`} className="insight-card" key={a.slug}><HomeVisual kind="insight" index={i+1} label={a.category}/><div className="card-content"><div className="article-meta"><span>{a.category}</span><time dateTime={a.date}>{a.date.replaceAll('-','. ')}</time></div><h3>{a.title}</h3><p>{a.summary}</p><span className="red-link">읽어보기 <ArrowUpRight size={16}/></span></div></Link>)}</div></Container></section><section className={layout.finalCta}><Container><div><p className="eyebrow">READY TO GROW?</p><h2>우리 브랜드의 다음 성장을<br/>고민하고 계신가요?</h2><p>광고를 더 집행하기 전에<br/>현재 브랜드가 어떻게 발견되고,<br/>왜 선택되지 않는지부터 확인해 보세요.</p></div><div className={layout.finalActions}><Button href="/contact">우리 브랜드 진단받기</Button><Button secondary href="/contact?type=project">프로젝트 상담하기</Button></div></Container></section></div></>}
