 'use client';
import Link from 'next/link';import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';import {usePathname} from 'next/navigation';
import {Menu,X,ChevronDown,ArrowRight} from 'lucide-react';
import {site} from '@/data/site';import {navigation} from '@/data/navigation';import {officialLogo} from '@/data/home-top';import styles from './header.module.css';
export function Logo({official=false}:{official?:boolean}={}){if(official)return <Link href="/" className={styles.officialLogo} aria-label="염원컴퍼니 홈"><Image src={officialLogo} alt="YUMONE COMPANY 공식 로고" width={367} height={176} priority/></Link>;return <Link href="/" className="logo" aria-label="염원컴퍼니 홈">{site.logo?<Image src={site.logo} alt="YUMONE COMPANY" width={180} height={52} priority/>:<><span className="logo-monogram" aria-hidden="true">Y</span><span><strong>YUMONE</strong><small>COMPANY</small></span></>}</Link>}

export function Header(){const path=usePathname().replace(/\/$/,'')||'/';const[open,setOpen]=useState(false);const[active,setActive]=useState<string|null>(null);const[expanded,setExpanded]=useState<string|null>(null);const root=useRef<HTMLElement>(null);const suppress=useRef(false);const current=navigation.find(g=>path===g.href||path.startsWith(g.href+'/'))?.key;
useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev}},[open]);
function close(){setOpen(false);setActive(null)}
function escape(e:React.KeyboardEvent){if(e.key==='Escape'){e.preventDefault();suppress.current=true;if(open){setOpen(false);document.getElementById('menu-toggle')?.focus()}else{const key=active;setActive(null);document.getElementById(`nav-${key}`)?.focus()}queueMicrotask(()=>{suppress.current=false})}if(open&&e.key==='Tab'){const nodes=[...root.current!.querySelectorAll<HTMLElement>('a,button')].filter(n=>n.getClientRects().length>0);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
return <header ref={root} className={styles.shell} onKeyDown={escape}><div className={styles.inner}><Logo official/><nav className={styles.desktop} aria-label="주 메뉴">{navigation.map(g=><div key={g.key} className={styles.item} onMouseEnter={()=>setActive(g.key)} onMouseLeave={()=>setActive(null)} onFocus={()=>{if(!suppress.current)setActive(g.key)}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setActive(null)}}><div className={styles.topRow}><Link id={`nav-${g.key}`} href={g.href} className={current===g.key?styles.selected:undefined} aria-current={path===g.href?'page':undefined} onClick={close}>{g.title}</Link><button aria-label={`${g.title} 하위 메뉴`} aria-expanded={active===g.key} aria-controls={`dropdown-${g.key}`} onClick={()=>setActive(active===g.key?null:g.key)}><ChevronDown size={16}/></button></div><div id={`dropdown-${g.key}`} className={styles.dropdown} hidden={active!==g.key}><Link className={styles.overview} href={g.href} onClick={close}>{g.title} 전체 보기 →</Link>{g.children.map(c=><Link href={c.href} key={c.href} onClick={close} aria-current={path===c.href?'page':undefined}>{c.title}</Link>)}</div></div>)}</nav><Link href="/contact" className={styles.cta} onClick={close}>우리 브랜드 무료 진단 <ArrowRight size={16}/></Link><button id="menu-toggle" className={styles.toggle} aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>{setOpen(!open);setExpanded(current||null)}}>{open?<X/>:<Menu/>}</button></div>
{open&&<nav id="mobile-menu" className={styles.mobile} aria-label="모바일 메뉴">{navigation.map(g=><div key={g.key}><button className={current===g.key?styles.selected:undefined} aria-expanded={expanded===g.key} aria-controls={`mobile-${g.key}`} onClick={()=>setExpanded(expanded===g.key?null:g.key)}>{g.title}<ChevronDown size={18}/></button><div id={`mobile-${g.key}`} hidden={expanded!==g.key}><Link href={g.href} onClick={close}>{g.title} 전체 보기 →</Link>{g.children.map(c=><Link key={c.href} href={c.href} aria-current={path===c.href?'page':undefined} onClick={close}>{c.title}</Link>)}</div></div>)}<Link className={styles.mobileCta} href="/contact" onClick={close}>우리 브랜드 무료 진단 →</Link></nav>}</header>}
