'use client';
import Link from 'next/link';
import Image from 'next/image';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {Menu,X,ArrowRight} from 'lucide-react';
import {nav,site} from '@/data/site';
import {officialLogo} from '@/data/home-top';
import styles from './header.module.css';
export function Logo({official=false}:{official?:boolean}={}){if(official)return <Link href="/" className={styles.officialLogo} aria-label="염원컴퍼니 홈"><Image src={officialLogo} alt="YUMONE COMPANY 공식 로고" width={367} height={176} priority/></Link>;return <Link href="/" className="logo" aria-label="염원컴퍼니 홈">{site.logo?<Image src={site.logo} alt="YUMONE COMPANY" width={180} height={52} priority/>:<><span className="logo-monogram" aria-hidden="true">Y</span><span><strong>YUMONE</strong><small>COMPANY</small></span></>}</Link>}
export function Header(){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const path=usePathname();const homeNav=[{label:"염원컴퍼니",href:"/about"},{label:"프랜차이즈 마케팅",href:"/services/franchise"},{label:"AI 검색 마케팅",href:"/services/ai-search"},{label:"콘텐츠 제작",href:"/services/marketing"},{label:"마케팅교육",href:"/education"},{label:"프로젝트",href:"/cases"},{label:"인사이트",href:"/insights"}];const menu=path==='/'?homeNav:nav;useEffect(()=>{const fn=()=>setScrolled(window.scrollY>15);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);useEffect(()=>{if(!open)return;const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);document.getElementById('menu-toggle')?.focus()}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)},[open]);return <header className={`header ${styles.header} ${path==='/'?styles.homeHeader:''} ${scrolled?'scrolled':''}`}><div className="container header-inner"><Logo official/><nav className="desktop-nav" aria-label="주 메뉴">{menu.map(n=><Link key={n.href} href={n.href} aria-current={path.startsWith(n.href)?'page':undefined}>{n.label}</Link>)}</nav><Link className="button header-cta" href="/contact">{path==='/'?'우리 브랜드 무료 진단':'상담 문의하기'} <ArrowRight size={17}/></Link><button id="menu-toggle" className="menu-toggle" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-menu" className="mobile-nav container" aria-label="모바일 메뉴">{menu.map(n=><Link key={n.href} href={n.href} onClick={()=>setOpen(false)}>{n.label}<ArrowRight size={18}/></Link>)}<Link className="button" href="/contact" onClick={()=>setOpen(false)}>상담 문의하기 →</Link></nav>}</header>}
