import {SubpageHero,RecruitChallenges} from './recruit-pilot';
import Link from 'next/link';
import {JsonLd,BreadSchema} from '@/lib/seo';
import {site} from '@/data/site';
import {services} from '@/data/services';
import {navigation,contactHref,type NavigationGroup,type NavigationItem} from '@/data/navigation';
import {insights,cases} from '@/data/content';
import {about} from '@/data/about';
import s from './sitemap-page.module.css';
export function articleHref(slug:string){return `/insight/column/${slug}`}
function CTA({group}:{group:NavigationGroup}){return <Link className={s.button} href={contactHref(group.key)}>{group.key==='education'?'기업·본사 교육 문의하기':group.key==='content'?'콘텐츠 제작 견적 문의하기':group.key==='ai-search'?'AI 검색 노출 확인하기':'우리 브랜드 성장 진단받기'} <span aria-hidden="true">→</span></Link>}
function faqItems({group,detail}:{group:NavigationGroup;detail?:NavigationItem}){const specific=group.key==='ai-search'?['검색 순위나 AI 추천을 보장하나요?','특정 순위나 AI 추천은 보장하지 않습니다. 브랜드 정보의 정확성, 콘텐츠 구조와 노출 현황을 점검하고 개선합니다.']:group.key==='education'?['교육 내용과 시간은 조정할 수 있나요?','참여자의 역할, 수준, 현장 과제를 먼저 확인한 뒤 커리큘럼과 실습 범위를 협의합니다.']:group.key==='project'?['공개된 고객사와 성과 수치를 볼 수 있나요?','고객사와 결과는 공개 승인과 근거가 확인된 자료만 게시합니다. 현재 상세 사례의 공개 범위는 상담 시 문의해 주세요.']:group.key==='about'?['어떤 분야를 함께 다루나요?','프랜차이즈 마케팅, 본사·SV·점주 교육, 컨설팅과 AI 검색 정보 정비를 연결합니다.']:['한 가지 서비스만 의뢰할 수 있나요?','현재 필요한 범위부터 협의할 수 있습니다. 진단 결과에 따라 우선순위를 정하고 필요한 작업을 제안합니다.'];return [specific,[`${detail?.title||group.title} 상담 전에 무엇을 준비하나요?`,'브랜드 또는 회사 소개, 운영 중인 채널과 현재 과제를 준비해 주세요. 자료가 부족하면 상담에서 먼저 정리합니다.'],['비용과 기간은 어떻게 정하나요?','브랜드 현황과 작업 범위, 제공 자료, 참여 인원 등을 확인한 후 협의합니다. 확인되지 않은 비용이나 기간을 일괄적으로 안내하지 않습니다.']]}
function FAQs({group,detail}:{group:NavigationGroup;detail?:NavigationItem}){return <section className={s.section}><JsonLd data={{'@type':'FAQPage',mainEntity:faqItems({group,detail}).map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}}/><div className={s.container}><p className={s.eyebrow}>FAQ</p><h2>상담 전에 확인해 주세요.</h2>{faqItems({group,detail}).map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>}
function Related({group,detail}:{group:NavigationGroup;detail?:NavigationItem}){let list=insights.filter(i=>group.key==='ai-search'?i.category.includes('AI')||i.category.includes('SEO'):group.key==='education'?i.category==='교육':true);if(detail?.href==='/insight/tips')list=insights.filter(i=>i.category==='교육');const project=group.key==='project';return <section className={s.section}><div className={s.container}><p className={s.eyebrow}>{project?'PROJECT CONTEXT':'RELATED INSIGHTS'}</p><h2>{project?'진행 방식과 공개 자료':'함께 살펴볼 콘텐츠'}</h2>{project&&<p className={s.lead}>고객명·로고·성과·후기는 공개 승인이 확인된 자료만 게시합니다. 아래는 현재 제공하는 서비스와 교육의 접근 방법입니다.</p>}{/* TODO: Replace with client-approved case data, logos, testimonial originals and consent metadata. */}<div className={s.grid}>{list.slice(0,3).map(i=><Link className={s.card} key={i.slug} href={articleHref(i.slug)}><small>{i.category}</small><h3>{i.title}</h3><p>{i.summary}</p><b>내용 읽기 →</b></Link>)}</div>{detail?.href==='/about/news'&&<p className={s.note}>공식 보도 자료는 출처와 공개 범위 확인 후 게시합니다. 현재 발행된 콘텐츠는 인사이트에서 확인할 수 있습니다.</p>}{detail?.href==='/insight/youtube'&&<a className={s.button} href="https://www.youtube.com/@프차언니/" target="_blank" rel="noopener noreferrer">공식 프차언니 유튜브 열기 ↗</a>}</div></section>}
export function SitemapPage({href}:{href:string}){const group=navigation.find(g=>href===g.href||g.children.some(c=>c.href===href));if(!group)return null;const detail=group.children.find(c=>c.href===href);const title=detail?.title||group.title;const founder=detail?.href==='/about/founder';const scopes=detail?.scope||group.children.map(c=>c.description);const recruit=href==='/franchise/recruit';return <div className={`${s.page} ${recruit?s.recruit:''}`}>{detail&&<BreadSchema items={[{label:group.title,href:group.href},{label:detail.title,href:detail.href}]}/>}{['franchise','ai-search','content','education'].includes(group.key)&&<JsonLd data={{'@type':'Service',name:title,description:detail?.description||group.description,url:site.url+href+'/',provider:{'@id':site.url+'/#organization'}}}/>}
{recruit?<SubpageHero group={group} detail={detail!}/>:(<section className={s.hero}><div className={s.container}><nav className={s.breadcrumb} aria-label="현재 위치"><Link href="/">HOME</Link><span>/</span>{detail?<><Link href={group.href}>{group.title}</Link><span>/</span><span aria-current="page">{detail.title}</span></>:<span>{group.title}</span>}</nav><p className={s.eyebrow}>{group.key.replace('-',' ').toUpperCase()} · YUMONE COMPANY</p><h1>{title}</h1><p className={s.headline}>{detail?.description||group.headline}</p><p className={s.lead}>{group.description}</p><CTA group={group}/></div></section>)}
<nav className={s.subnav} aria-label={`${group.title} 하위 메뉴`}><div className={s.container}><Link href={group.href} aria-current={!detail?'page':undefined}>전체 소개</Link>{group.children.map(c=><Link key={c.href} href={c.href} aria-current={href===c.href?'page':undefined}>{c.title}</Link>)}</div></nav>
{recruit?<RecruitChallenges group={group} detail={detail!}/>:(<section className={s.section}><div className={`${s.container} ${s.split}`}><div><p className={s.eyebrow}>YOUR CHALLENGE</p><h2>{group.key==='about'?'이런 파트너가 필요하신가요?':'지금 해결해야 할 과제부터.'}</h2><p className={s.lead}>{group.audience}</p></div><div className={s.problems}>{(detail?[detail.problem!,...group.problems]:group.problems).map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</div></div></section>)}
<section id={recruit?'recruit-scope':undefined} className={`${s.section} ${s.warm}`}><div className={s.container}><p className={s.eyebrow}>OUR APPROACH</p><h2>{detail?detail.description:'문제와 실행을 하나의 흐름으로 연결합니다.'}</h2>{founder?<div className={s.founder}><img src="/images/pdf-reference/founder-portrait.jpg" alt="염혜단 대표" width="1200" height="1800"/><div><h3>염혜단 · 염원컴퍼니 대표</h3><p>{about.ceo.description}</p><ul>{about.ceo.careers.map(c=><li key={c}>{c}</li>)}</ul></div></div>:<p className={s.lead}>{detail?`${detail.description} ${group.description}`:'브랜드의 현재 상황을 확인하고 필요한 범위를 정합니다. 실행할 담당자와 활용할 결과물까지 함께 고려합니다.'}</p>}
{detail?<><h3 className={s.scopeTitle}>제공 범위 · 확인 항목</h3><div className={s.grid}>{scopes.map((x,i)=><div className={s.card} key={x}><small>0{i+1}</small><h3>{x}</h3><p>{group.key==='education'?'실무 수준과 참여자의 과제에 맞춰 사례와 실습을 구성합니다.':'현재 보유 자료와 운영 현황을 확인한 후 구체적인 적용 범위를 협의합니다.'}</p></div>)}</div></>:<div className={s.grid}>{group.children.map((c,i)=><Link className={s.card} href={c.href} key={c.href}><small>0{i+1}</small><h3>{c.title}</h3><p>{c.description}</p><b>자세히 보기 →</b></Link>)}</div>}
{detail?.href==='/about/company'&&<div>{about.company.paragraphs.map(x=><p className={s.lead} key={x}>{x}</p>)}<h3>{about.philosophy.title}</h3><p className={s.lead}>{about.philosophy.description}</p></div>}<div className={s.inlineCTA}><span>우리 브랜드에 필요한 범위를 함께 정리해 보세요.</span><CTA group={group}/></div></div></section>
{detail&&<section className={s.section}><div className={s.container}><p className={s.eyebrow}>PROCESS</p><h2>{group.key==='about'||group.key==='insight'?'자료 확인부터 상담까지.':'현황 진단에서 실행과 개선까지.'}</h2><ol className={s.process}>{[['현황 확인','브랜드 자료, 고객과 운영 중인 채널을 살펴봅니다.'],['과제 정의','목표와 해결 우선순위, 진행 범위를 합의합니다.'],['설계·진행',group.key==='education'?'역할별 교육과 실습을 진행합니다.':'합의한 범위에 따라 콘텐츠와 실행 방향을 구체화합니다.'],['점검·개선','적용 결과와 피드백을 확인하고 후속 과제를 정리합니다.']].map(([a,b],i)=><li key={a}><small>0{i+1}</small><h3>{a}</h3><p>{b}</p></li>)}</ol></div></section>}
{detail&&<section className={`${s.section} ${s.dark}`}><div className={s.container}><p className={s.eyebrow}>WHY YUMONE</p><h2>현장을 알기에,<br/>실행 가능한 전략을 만듭니다.</h2><div className={s.grid}>{about.values.map(v=><div key={v.title}><h3>{v.title}</h3><p>{v.description}</p></div>)}</div></div></section>}
<IntegratedContent href={href}/><Related group={group} detail={detail}/><FAQs group={group} detail={detail}/><section className={`${s.section} ${s.dark}`}><div className={s.container}><p className={s.eyebrow}>YOUR NEXT STEP</p><h2>{title},<br/>현재 브랜드의 과제부터 이야기해 주세요.</h2><p className={s.lead}>필요한 서비스와 진행 범위는 상담을 통해 함께 정리합니다.</p><CTA group={group}/></div></section></div>}
export function ExistingArticle({slug}:{slug:string}){const item=insights.find(i=>i.slug===slug)!;return <article className={s.page}><section className={s.hero}><div className={s.container}><ContentBreadcrumb href={articleHref(slug)} title={item.title}/><p className={s.eyebrow}>{item.category}</p><h1>{item.title}</h1><p className={s.lead}>{item.summary}</p><time dateTime={item.date}>{item.date}</time></div></section><div className={s.article}>{item.sections.map(x=><section key={x.title}><h2>{x.title}</h2><p>{x.text}</p></section>)}<Link className={s.button} href="/contact?service=franchise">우리 브랜드에 적용하기 →</Link></div></article>}
export function ExistingCase({slug}:{slug:string}){const item=cases.find(i=>i.slug===slug)!;return <article className={s.page}><section className={s.hero}><div className={s.container}><ContentBreadcrumb href={`/project/marketing/${slug}`} title={item.title}/><p className={s.eyebrow}>PROJECT FRAMEWORK</p><h1>{item.title}</h1><p className={s.lead}>{item.service}</p><p className={s.note}>기존 프로젝트에 등록된 사례 구성 예시입니다. 실제 고객사나 검증된 성과를 의미하지 않습니다.</p></div></section><section className={s.section}><div className={s.container}><h2>확인할 과제와 진행 범위</h2><p>{item.problem}</p><ul>{item.tags.map(t=><li key={t}>{t}</li>)}</ul><p>공개 승인된 수행 범위와 결과 자료가 확인되면 상세 사례를 추가합니다.</p><Link className={s.button} href="/contact?service=franchise">유사 과제 상담하기 →</Link></div></section></article>}

function IntegratedContent({href}:{href:string}){const slug=href==='/franchise/sales'?'marketing':href==='/ai-search/diagnosis'?'ai-search':href==='/content/brand-film'?'franchise':null;if(!slug)return null;const source=services.find(s=>s.slug===slug)!;const items=slug==='franchise'?source.deliverables.filter(x=>x.includes('매뉴얼')):source.deliverables;return <section className={s.section}><div className={s.container}><p className={s.eyebrow}>CONNECTED EXPERTISE</p><h2>{slug==='franchise'?'운영 매뉴얼도 브랜드 콘텐츠로 연결합니다.':'기존 운영 자료에서 실행 과제를 찾습니다.'}</h2><p className={s.lead}>{source.summary}</p><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div></section>}
function ContentBreadcrumb({href,title}:{href:string;title:string}){const group=navigation.find(g=>href.startsWith(g.href+'/'))!;const child=group.children.find(c=>href.startsWith(c.href+'/'))!;const items=[{label:group.title,href:group.href},{label:child.title,href:child.href},{label:title,href}];return <><BreadSchema items={items}/><nav className={s.breadcrumb} aria-label="현재 위치"><Link href="/">홈</Link>{items.map((x,i)=><span key={x.href}> / {i===items.length-1?<span aria-current="page">{x.label}</span>:<Link href={x.href}>{x.label}</Link>}</span>)}</nav></>}
