import Image from 'next/image';
import Link from 'next/link';
import {navigation,contactHref,companyContact} from '@/data/navigation';
import {about} from '@/data/about';
import {insights} from '@/data/content';
import {siteCopy,serviceChoices,workExamples} from '@/data/site-quality';
import {BreadSchema,JsonLd} from '@/lib/seo';
import s from './site-quality.module.css';

export function QualityHero({href,title,description,label,children}:{href:string;title?:string;description?:string;label?:string;children?:React.ReactNode}){
 const c=siteCopy[href];const group=navigation.find(g=>href===g.href||href.startsWith(g.href+'/'));const current=title||c?.title||'';
 return <section className={s.hero}><div className={s.container}><nav className={s.breadcrumb} aria-label="현재 위치"><Link href="/">홈</Link><span>/</span>{group&&href!==group.href&&<><Link href={group.href}>{group.title}</Link><span>/</span></>}<span aria-current="page">{label||group?.children.find(x=>x.href===href)?.title||group?.title||current.replace('\n',' ')}</span></nav><p className={s.kicker}>{label||group?.title||'YUMONE COMPANY'}</p><h1>{current}</h1><p className={s.lead}>{description||c?.description}</p>{children}</div></section>;
}
function Section({title,label,children,id}:{title:string;label?:string;children:React.ReactNode;id?:string}){return <section id={id} className={s.section}><div className={s.container}>{label&&<p className={s.kicker}>{label}</p>}<h2>{title}</h2>{children}</div></section>}
export function QualityCTA({service='other'}:{service?:string}){return <section className={s.final}><div className={s.container}><div><h2>필요한 업무가 아직 정리되지 않았어도 괜찮습니다.</h2><p>현재 운영 상황과 가장 해결하고 싶은 문제를 알려주세요.<br/>검토할 자료와 진행 범위를 함께 정리하겠습니다.</p></div><Link className={s.button} href={service==='other'?'/contact/':contactHref(service)}>우리 회사 상황 상담하기 <span aria-hidden="true">→</span></Link></div></section>}
function PageLinks({items}:{items:{title:string;description:string;href:string}[]}){return <ul className={s.links}>{items.map(i=><li key={i.href}><Link href={i.href}><h3>{i.title}</h3><p>{i.description}</p><span aria-hidden="true">→</span></Link></li>)}</ul>}
function Proof({portrait=false}:{portrait?:boolean}){return <div className={s.proof}><div><h3>염혜단 대표 · 프랜차이즈 실무와 교육</h3><p>본사에서 정할 기준과 가맹점에서 실행할 일을 구분해 살펴봅니다. 다음은 기존 회사 소개 자료에 안내된 경력입니다.</p><ul>{about.ceo.careers.map(x=><li key={x}>{x}</li>)}</ul>{!portrait&&<Link className={s.textLink} href="/about/founder/">대표 경력 확인하기 →</Link>}</div><figure><Image src={portrait?'/images/pdf-reference/founder-portrait.jpg':'/images/pdf-reference/how-work-ai.webp'} alt={portrait?'염혜단 대표':'염혜단 대표의 온라인 마케팅 강의 장면'} width={portrait?306:422} height={portrait?408:254} loading="lazy"/><figcaption>{portrait?'기존 회사 소개 자료 · 염혜단 대표':'제공된 온라인 마케팅 강의 자료'}</figcaption></figure></div>}
function Examples({onlyEducation=false}:{onlyEducation?:boolean}){return <><p className={s.notice}>업무 이해를 위한 구성 예시입니다. 실제 고객명·수행 기간·검증된 성과를 나타내지 않습니다.</p><PageLinks items={Object.entries(workExamples).filter(([key])=>!onlyEducation||key==='field-education').map(([slug,x])=>({href:`/project/marketing/${slug}/`,title:x.title,description:`${x.situation}. ${x.outputs.join(' · ')}의 구성을 확인합니다.`}))}/></>}
function ArticleList({href}:{href:string}){const list=insights.filter(i=>href.includes('ai-search')?['AI','SEO · AEO'].includes(i.category):href.endsWith('/tips')?i.category==='교육':href.endsWith('/column')?i.category==='프랜차이즈':true);return <div className={s.articleList}>{list.map(i=><article key={i.slug}><p className={s.meta}>{i.category} · <time dateTime={i.date}>{i.date}</time></p><h3><Link href={`/insight/column/${i.slug}/`}>{i.title} →</Link></h3><p>{i.summary}</p></article>)}</div>}

export function QualityHome(){return <div className={s.page} data-quality="site-v2"><section className={`${s.hero} ${s.homeHero}`}><div className={s.container}><p className={s.kicker}>프랜차이즈 본사·SV·점주를 위한 마케팅과 교육</p><div className={s.homeGrid}><div><h1>{siteCopy['/'].title}</h1><p className={s.lead}>{siteCopy['/'].description}</p><div className={s.actions}><Link className={s.button} href="/contact/">마케팅·교육 상담하기 →</Link><a className={s.textLink} href="#services">서비스 살펴보기 ↓</a></div></div><dl className={s.facts}><div><dt>경험</dt><dd>20년+ 프랜차이즈 실무</dd></div><div><dt>업무</dt><dd>콘텐츠 제작 · 광고 운영 · 브랜드 정보 정비</dd></div><div><dt>교육</dt><dd>본사 직원 · SV · 점주 · 소상공인</dd></div></dl></div></div></section>
 <Section id="services" label="서비스 선택" title="지금 필요한 업무부터 살펴보세요."><div className={s.choices}>{serviceChoices.map((c,i)=><article key={c.href}><p className={s.kicker}>0{i+1} / {c.title}</p><h3>{c.need}</h3><p>{c.text}</p><div className={s.actions}><Link className={s.textLink} href={c.href}>{c.title} 범위 보기 →</Link><Link className={s.smallLink} href={c.detail}>대표 서비스 상세</Link></div></article>)}</div></Section>
 <Section label="경험과 근거" title="본사와 가맹점의 업무를 이해합니다."><Proof/></Section>
 <Section label="업무와 결과물" title="어떤 자료를 확인하게 되는지 먼저 보세요."><Examples/></Section>
 <QualityCTA/></div>}

export function QualityPage({href}:{href:string}){
 const group=navigation.find(g=>href===g.href||g.children.some(c=>c.href===href));if(!group)return null;
 const child=group.children.find(c=>c.href===href);const isAbout=group.key==='about';const isProject=group.key==='project';
 return <div className={s.page} data-quality="site-v2"><BreadSchema items={child?[{label:group.title,href:group.href},{label:child.title,href}]:[{label:group.title,href}]}/><QualityHero href={href}/><nav className={s.subnav} aria-label={`${group.title} 하위 메뉴`}><div className={s.container}><Link href={group.href} aria-current={!child?'page':undefined}>전체 소개</Link>{group.children.map(c=><Link href={c.href} key={c.href} aria-current={c.href===href?'page':undefined}>{c.title}</Link>)}</div></nav>
 {isAbout?<>
  {href==='/about/founder'?<Section title="경력과 담당 분야"><Proof portrait/></Section>:href==='/about/news'?<Section title="현재 공개된 콘텐츠"><ArticleList href={href}/><p className={s.notice}>별도로 확인된 언론 보도 원문은 현재 게시되어 있지 않습니다.</p><a className={s.textLink} href="https://www.youtube.com/@프차언니/" target="_blank" rel="noopener noreferrer">프차언니 공식 유튜브 열기 ↗</a></Section>:<>
   <Section title={href==='/about/difference'?'함께 일할 때 확인하는 세 가지':'본사의 과제를 실행 업무로 나눕니다.'}><div className={s.three}>{[{title:'브랜드가 전달할 정보',text:'고객이 확인할 서비스·창업 정보와 실제 제공 범위를 대조합니다.'},{title:'내부 담당자의 역할',text:'기존 인력과 대행사의 업무를 확인하고 외부에 맡길 제작·운영 범위를 정합니다.'},{title:'현장에서 적용할 기준',text:'가맹점 여건과 담당자 수준을 확인해 실행 가이드와 교육 내용을 구성합니다.'}].map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></Section>
   {href!=='/about/difference'&&<Section title="확인 가능한 경험"><Proof/></Section>}
   <Section title="관련 업무를 확인하세요."><PageLinks items={serviceChoices.map(c=>({title:c.title,description:c.text,href:c.href}))}/></Section>
  </>}
 </>:isProject?<>
  {href==='/project/partners'||href==='/project/reviews'?<Section title={href.endsWith('partners')?'명단보다 수행 범위부터 확인하세요.':'후기 대신 확인할 수 있는 정보'}><p>공개 승인을 받은 {href.endsWith('partners')?'고객사 명단·로고':'후기 원문'}가 확보되면 해당 업무의 맥락과 함께 안내합니다. 현재는 아래 자료로 의뢰 범위와 협업 방식을 확인할 수 있습니다.</p><PageLinks items={[{href:'/project/marketing/',title:'업무 구성 예시',description:'고객 상황, 수행할 업무, 확인할 자료를 구분해 살펴봅니다.'},{href:'/about/founder/',title:'담당자의 경력',description:'기존 회사 소개 자료에 안내된 경험과 활동을 확인합니다.'},{href:'/contact/',title:'협업 범위 상담',description:'보유 자료와 필요한 업무를 정리해 문의합니다.'}]}/></Section>:<>
   {(href==='/project'||href==='/project/education')&&<Section title="공개된 현장 자료"><div className={s.proof}><div><h3>슈퍼바이저 마케팅 교육 현장</h3><p>제공된 사진에서 강의와 노트북을 활용하는 교육 현장을 확인할 수 있습니다. 고객명, 개별 진행 기간, 교육 성과 수치는 공개 자료가 확인되지 않아 기재하지 않습니다.</p><Link className={s.textLink} href="/education/supervisor/">SV 교육 내용과 활용 자료 보기 →</Link></div><figure><Image src="/images/supervisor-marketing-training.jpg" alt="강사와 수강생이 함께하는 슈퍼바이저 마케팅 교육 현장" width={960} height={720} loading="lazy"/><figcaption>공개 교육 현장 자료</figcaption></figure></div></Section>}
   <Section title={href==='/project/education'?'교육 과제와 실습 자료의 구성':'과제별 업무 구성 예시'}><Examples onlyEducation={href==='/project/education'}/></Section>
  </>}
 </>:<Section title={href==='/insight/youtube'?'공식 영상 채널':'주제에 맞는 글을 읽어보세요.'}>{href==='/insight/youtube'?<><p>프랜차이즈 마케팅과 교육에 관한 영상은 공식 채널에서 확인할 수 있습니다. 영상의 게시 시점과 설명을 함께 확인해 주세요.</p><a className={s.button} href="https://www.youtube.com/@프차언니/" target="_blank" rel="noopener noreferrer">프차언니 유튜브에서 영상 보기 ↗</a></>:<ArticleList href={href}/>}</Section>}
 <QualityCTA service={isAbout||isProject?'other':href.includes('ai-search')?'ai-search':href.endsWith('tips')?'education':'franchise'}/></div>;
}

export function QualityArticle({slug}:{slug:string}){const item=insights.find(i=>i.slug===slug)!;const service=item.category==='교육'?'education':['AI','SEO · AEO'].includes(item.category)?'ai-search':'franchise';return <div className={s.page} data-quality="site-v2"><QualityHero href={`/insight/column/${slug}`} title={item.title} description={item.summary} label={item.category}/><article className={s.article}><p className={s.meta}><time dateTime={item.date}>{item.date}</time> · 염원컴퍼니</p>{item.sections.map(x=><section key={x.title}><h2>{x.title}</h2><p>{x.text}</p></section>)}<Link className={s.textLink} href={service==='education'?'/education/':service==='ai-search'?'/ai-search/':'/franchise/'}>관련 서비스 범위 확인하기 →</Link><JsonLd data={{'@type':'Article',headline:item.title,description:item.summary,datePublished:item.date,author:{'@type':'Organization',name:'염원컴퍼니'}}}/></article><QualityCTA service={service}/></div>}
export function QualityCase({slug}:{slug:string}){const x=workExamples[slug];return <div className={s.page} data-quality="site-v2"><QualityHero href={`/project/marketing/${slug}`} title={x.title} description="업무의 흐름과 자료를 이해하기 위한 구성 예시입니다. 실제 수행 실적이나 검증된 성과를 의미하지 않습니다." label="업무 구성 예시"/><Section title="상황 · 업무 · 자료를 구분해 확인하세요."><dl className={s.caseRows}><div><dt>상황 · 구성 예시</dt><dd>{x.situation}</dd></div><div><dt>협의할 업무</dt><dd><ul>{x.work.map(a=><li key={a}>{a}</li>)}</ul></dd></div><div><dt>확인할 자료</dt><dd><ul>{x.outputs.map(a=><li key={a}>{a}</li>)}</ul></dd></div><div><dt>기간·수행 실적</dt><dd>실제 고객 프로젝트가 아닌 구성 예시이므로 기간과 성과는 표시하지 않습니다.</dd></div></dl><Link className={s.button} href={x.service}>해당 서비스 제공 범위 보기 →</Link></Section><QualityCTA service={x.service.split('/')[1]}/></div>}

export function QualitySitemap(){return <div className={s.page} data-quality="site-v2"><QualityHero href="/site-map" label="전체 사이트맵"/><Section title="전체 메뉴"><div className={s.sitemap}>{navigation.map(g=><section key={g.href}><h3><Link href={g.href}>{g.title}</Link></h3><ul>{g.children.map(c=><li key={c.href}><Link href={c.href}>{c.title}</Link></li>)}</ul></section>)}</div><Link className={s.textLink} href="/contact/">마케팅·교육 상담 안내 →</Link></Section></div>}

export function QualityLegal({privacy}:{privacy:boolean}){return <div className={s.page} data-quality="site-v2"><QualityHero href={privacy?'/privacy':'/terms'} title={privacy?'개인정보처리방침':'홈페이지 이용 안내'} description={privacy?'현재 문의 작성 화면의 처리 방식과 운영 정책 확인이 필요한 범위를 안내합니다.':'서비스 정보와 업무 구성 예시를 이용할 때 확인할 내용을 안내합니다.'} label={privacy?'개인정보 안내':'이용 안내'}/><article className={s.article}>{privacy?<>
 <section><h2>문의 작성 화면의 처리 방식</h2><p>입력 내용은 현재 브라우저 화면에서 이메일 초안으로 정리합니다. 웹 서버나 외부 접수 서비스에 전송하거나 브라우저 저장소에 보관하지 않습니다. 화면을 벗어나거나 새로고침하면 입력 내용이 사라질 수 있습니다.</p><p>이메일 앱 열기를 누르면 입력 내용이 기기의 이메일 앱으로 전달됩니다. 실제 전송은 이용자가 이메일 앱에서 발송할 때 이루어집니다. 복사 버튼은 이용자의 선택에 따라 문의 내용을 기기 클립보드에 복사합니다.</p></section>
 <section><h2>이메일·전화 문의와 개인정보</h2><p>상담에 필요한 회사명, 연락 방법과 업무 상황만 전달해 주세요. 계정 비밀번호, 주민등록번호 등 상담에 불필요한 정보는 입력하지 마세요.</p><p>이메일·전화로 전달된 정보의 보유 기간, 파기 절차, 개인정보 보호 담당자, 처리위탁·국외이전 및 배포 플랫폼 접속 로그의 처리 기준은 운영자의 확정이 필요합니다. 현재 안내를 확정된 전체 처리방침으로 보아서는 안 됩니다.</p></section>
 <section><h2>정보 처리 관련 문의</h2><p>현재 공개된 회사 연락처로 정보 처리와 관련한 확인을 요청할 수 있습니다.</p><a href={`mailto:${companyContact.email}`}>{companyContact.email}</a><br/><a href={`tel:${companyContact.tel}`}>{companyContact.phone}</a></section>
 </>:<><section><h2>서비스 안내의 범위</h2><p>이 홈페이지는 염원컴퍼니의 마케팅·콘텐츠 제작·교육 업무와 상담 방법을 안내합니다. 개별 프로젝트의 제공 항목, 비용과 일정은 상담 및 별도 계약에서 확정합니다.</p></section><section><h2>실제 자료와 구성 예시</h2><p>구성 예시로 표시된 내용은 업무를 설명하기 위한 자료이며 실제 고객 프로젝트나 검증된 성과를 의미하지 않습니다. 고객명·후기·기간·성과는 공개 자료가 확인된 범위에서만 안내합니다.</p></section><section><h2>문의와 외부 서비스</h2><p>문의 작성 화면은 이메일 초안을 준비하는 기능입니다. 이메일을 직접 발송해야 회사에 전달되며, 홈페이지에서 접수 여부를 확인하거나 완료를 보장하지 않습니다. 유튜브와 이메일 앱 등 외부 서비스는 해당 서비스로 이동하여 이용합니다.</p></section><section><h2>이용 조건 확인</h2><p>이 문서는 현재 사이트 이용 방법을 설명하는 안내입니다. 콘텐츠 이용 범위와 시행일 등 확정 약관에 필요한 운영 정책은 회사의 확인 후 반영할 예정입니다.</p></section></> }<Link className={s.textLink} href="/contact/">상담 안내로 돌아가기 →</Link></article></div>}
