import Image from 'next/image';import Link from 'next/link';
import type {BlogPost,BlogImage,BlogBlock} from '@/lib/blog-types';
import {blogCTA,cardPosts,postHref} from '@/lib/blog';
import {site} from '@/data/site';import {JsonLd} from '@/lib/seo';
import {BlogToc} from './blog-toc';import {BlogCardView} from './blog-card';import s from './blog.module.css';
function Figure({image,priority=false}:{image:BlogImage;priority?:boolean}){return <figure className={s.figure}><Image src={image.src} alt={image.alt} width={image.width} height={image.height} sizes="(max-width:900px) 90vw,800px" priority={priority} loading={priority?undefined:'lazy'}/><figcaption>{image.caption}{image.kind==='generated'&&<> · 이해를 돕기 위한 AI 생성 이미지</>}</figcaption></figure>}
function Block({block,post}:{block:BlogBlock;post:BlogPost}){switch(block.type){case 'heading':return block.level===3?<h3 id={block.id} tabIndex={-1}>{block.text}</h3>:<h2 id={block.id} tabIndex={-1}>{block.text}</h2>;case 'paragraph':return <p>{block.text}</p>;case 'quote':return <blockquote>{block.text}</blockquote>;case 'list':return block.ordered?<ol>{block.items?.map((t,i)=><li key={i}>{t}</li>)}</ol>:<ul>{block.items?.map((t,i)=><li key={i}>{t}</li>)}</ul>;case 'table':return <div className={s.tableWrap} tabIndex={0} role="region" aria-label="본문 표"><table><tbody>{block.rows?.map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0?<th scope="col" key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;case 'link':return block.href&&/^https?:\/\//.test(block.href)?<p><a href={block.href} target="_blank" rel="noopener noreferrer">{block.text||block.href} ↗</a></p>:<p>{block.text}</p>;case 'image':{const image=post.images.find(i=>i.id===block.imageId&&i.status==='ready'&&i.rights==='approved');return image?<Figure image={image}/>:null}}}
export function BlogArticle({post}:{post:BlogPost}){const images=post.images.filter(i=>i.status==='ready'&&i.rights==='approved');const cover=images.find(i=>i.role==='thumbnail');const toc=post.blocks.filter(b=>b.type==='heading'&&b.id&&b.text).map(b=>({id:b.id!,text:b.text!,level:b.level===3?3 as const:2 as const}));const related=cardPosts().filter(p=>p.id!==post.id).sort((a,b)=>Number(b.category===post.category)-Number(a.category===post.category)).slice(0,3);const cta=blogCTA[post.ctaCategory||post.category];const canonical=site.url+postHref(post);
 return <div className={s.page}><div className={s.container}><div className={s.reader}><BlogToc items={toc} category={post.category}/><article className={s.article}><header className={s.articleHeader}><Link href="/insight/" className={s.back}>블로그</Link><p className={s.category}>{post.category}</p><h1>{post.title}</h1><div className={s.meta}><span>{post.author||'염원컴퍼니'}</span><span>발행 <time dateTime={post.publishedAt}>{post.publishedAt.slice(0,10).replaceAll('-','. ')}</time></span>{post.modifiedAt&&post.modifiedAt!==post.publishedAt&&<span>수정 <time dateTime={post.modifiedAt}>{post.modifiedAt.slice(0,10).replaceAll('-','. ')}</time></span>}</div></header>{cover&&<Figure image={cover} priority/>}<div className={s.summary}><strong>핵심 요약</strong><p>{post.summary}</p></div><div className={s.body}>{post.blocks.map((block,i)=><div key={block.id||i}><Block block={block} post={post}/>{block.type==='heading'&&images.filter(image=>image.role==='body'&&image.headingId===block.id&&!post.blocks.some(b=>b.type==='image'&&b.imageId===image.id)).map(image=><Figure key={image.id} image={image}/>)}</div>)}</div><footer className={s.articleEnd}>{post.sourceUrl&&<p className={s.source}><a href={post.sourceUrl} target="_blank" rel="noopener noreferrer">네이버 원문 보기 ↗</a>{post.importedAt&&<> · 홈페이지 이관 {post.importedAt.slice(0,10)}</>}</p>}<Link className={s.cta} href={cta.href}>{cta.label} →</Link></footer>{related.length>0&&<section className={s.related}><h2>관련 글</h2><div className={s.grid}>{related.map(p=><BlogCardView key={p.id} post={p} heading="h3"/>)}</div></section>}<Link className={s.back} href="/insight/">← 블로그 목록으로</Link></article></div></div><JsonLd data={{'@type':'BlogPosting',headline:post.title,description:post.summary,url:canonical,mainEntityOfPage:canonical,datePublished:post.publishedAt,...(post.modifiedAt?{dateModified:post.modifiedAt}:{}),author:{'@type':post.author==='염원컴퍼니'?'Organization':'Person',name:post.author||'염원컴퍼니'},publisher:{'@id':site.url+'/#organization'},...(cover?{image:site.url+cover.src}:{}),articleSection:post.category,keywords:post.tags.join(', ')}}/><JsonLd data={{'@type':'BreadcrumbList',itemListElement:[{name:'홈',url:site.url+'/'},{name:'블로그',url:site.url+'/insight/'},{name:post.title,url:canonical}].map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,item:p.url}))}}/></div>;
}
