import 'server-only';
import {inflateRawSync} from 'node:zlib';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fixtureEnabled} from './notion';
import type {Attachment} from './core';
export const maxFileBytes=10*1024*1024;
const types:Record<string,string>={pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
export function safeFileURL(input:string){const u=new URL(input);if(u.protocol!=='https:'||u.username||u.password||u.port)throw Error('지원하지 않는 파일 저장소입니다.');const known=u.hostname==='prod-files-secure.s3.us-west-2.amazonaws.com'||u.hostname==='s3.us-west-2.amazonaws.com'||u.hostname==='s3.amazonaws.com';if(!known)throw Error('노션에 직접 업로드한 파일만 지원합니다.');return u;}
export function validateDocument(bytes:Buffer,name:string){const ext=name.split('.').pop()?.toLowerCase()||'';if(!types[ext]||bytes.length<50||bytes.length>maxFileBytes)throw Error('PDF·DOCX·XLSX 10MB 이하 문서만 지원합니다.');if(ext==='pdf'){const s=bytes.toString('latin1');if(!s.startsWith('%PDF-')||!s.includes('%%EOF')||/\/JavaScript|\/JS\b|\/Launch|\/EmbeddedFile|\/OpenAction/.test(s))throw Error('PDF 파일 내용을 확인해 주세요.');}else{let at=bytes.length-22;while(at>=Math.max(0,bytes.length-65557)&&bytes.readUInt32LE(at)!==0x06054b50)at--;if(at<0)throw Error('올바른 문서 압축 형식이 아닙니다.');let pos=bytes.readUInt32LE(at+16),total=0;const names:string[]=[];let manifest='';for(let i=0;i<bytes.readUInt16LE(at+10);i++){if(pos+46>bytes.length||bytes.readUInt32LE(pos)!==0x02014b50)throw Error('손상된 문서입니다.');const size=bytes.readUInt32LE(pos+24),compressed=bytes.readUInt32LE(pos+20),length=bytes.readUInt16LE(pos+28),name=bytes.toString('utf8',pos+46,pos+46+length);total+=size;if(total>50*1024*1024||/vbaProject|embeddings\/|\.exe$|\.js$|\.html$/i.test(name)||name.includes('..'))throw Error('지원하지 않는 문서 내용입니다.');names.push(name);if(name==='[Content_Types].xml'){const off=bytes.readUInt32LE(pos+42),start=off+30+bytes.readUInt16LE(off+26)+bytes.readUInt16LE(off+28),raw=bytes.subarray(start,start+compressed);manifest=(bytes.readUInt16LE(pos+10)===0?raw:inflateRawSync(raw,{maxOutputLength:1024*1024})).toString('utf8');}pos+=46+length+bytes.readUInt16LE(pos+30)+bytes.readUInt16LE(pos+32);}if(!manifest||/macroEnabled|vbaProject/i.test(manifest)||!names.includes(ext==='docx'?'word/document.xml':'xl/workbook.xml'))throw Error('확장자와 문서 내용이 다릅니다.');}return types[ext];}
export async function loadAttachment(file:Attachment){if(fixtureEnabled()&&file.url.startsWith('fixture:')&&process.env.SUPPORT_TEST_FILE_ROOT){const root=path.resolve(process.env.SUPPORT_TEST_FILE_ROOT),target=path.resolve(root,file.url.slice(8));if(!target.startsWith(root+path.sep))throw Error('Invalid fixture');const bytes=await readFile(target);return {bytes,mime:validateDocument(bytes,file.name),name:file.name,size:bytes.length};}if(file.type!=='file')throw Error('노션에 직접 업로드한 파일만 지원합니다.');const url=safeFileURL(file.url);const r=await fetch(url,{cache:'no-store',redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok||Number(r.headers.get('content-length')||0)>maxFileBytes||r.headers.get('content-type')?.includes('text/html'))throw Error('파일을 불러올 수 없습니다.');const reader=r.body?.getReader();if(!reader)throw Error('빈 파일입니다.');const chunks:Uint8Array[]=[];let count=0;while(true){const {done,value}=await reader.read();if(done)break;count+=value.byteLength;if(count>maxFileBytes){await reader.cancel();throw Error('파일 크기 제한을 초과했습니다.');}chunks.push(value);}const bytes=Buffer.concat(chunks);return {bytes,mime:validateDocument(bytes,file.name),name:file.name,size:bytes.length};}
