import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {metadata as makeMetadata} from '@/lib/seo';
import {companyContact} from '@/data/navigation';
import {supportKinds,selectEntries,paginate,type SupportKind} from '@/lib/support/core';
import {publicSupport} from '@/lib/support/public';
import {SupportHero,Consultation,Notices,ResourceCards,Empty,Search,Filters,Pager} from '@/components/support/shared';
import {SupportNavigation} from '@/components/support/navigation';
import s from '@/components/support/support.module.css';
export const dynamic='force-dynamic';
type Props={params:Promise<{section:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
const descriptions={notices:'염원컴퍼니의 서비스 소식과 교육·운영 안내를 확인하세요.',faq:'마케팅과 교육의 진행 방식, 준비 사항을 확인하세요.',resources:'본사 마케팅과 가맹점 운영에 활용할 실무 자료를 확인하세요.',inquiry:'가맹모집·가맹점 매출·AI 마케팅·교육 중 현재 고민을 알려주세요.'};
export async function generateMetadata({params,searchParams}:Props):Promise<Metadata>{const {section}=await params,q=await searchParams;const name=section==='inquiry'?'1:1 문의':supportKinds[section as SupportKind];if(!name)return {robots:{index:false,follow:false}};return {...makeMetadata(name,descriptions[section as keyof typeof descriptions],'/support/'+section),...(q.q||q.page||q.category?{robots:{index:false,follow:true}}:{})};}
export default async function Section({params,searchParams}:Props){const {section}=await params;if(section!=='inquiry'&&!Object.hasOwn(supportKinds,section))notFound();const title=section==='inquiry'?'1:1 문의':supportKinds[section as SupportKind];if(section==='inquiry')return <><SupportHero title={title} description={descriptions.inquiry}/><div className={s.container}><SupportNavigation/><section className={s.section}><h2>전화·이메일로 상담하기</h2><p className={s.lead}>현재 온라인 접수 대신 전화와 이메일로 문의를 받고 있습니다.<br/>회사명·브랜드명과 회신받을 연락처, 현재 고민을 알려주세요.</p><div className={s.contact}><a className={s.button} href={`tel:${companyContact.tel}`}>{companyContact.phone}</a><a className={s.button} href={`mailto:${companyContact.email}`}>{companyContact.email}</a></div><p className={s.note}>이 화면에서는 개인정보를 입력받거나 저장하지 않습니다. 문의 내용은 공개 게시판에 등록되지 않습니다.</p><Link href="/contact/?from=support" className={s.footerLink}>기존 상담 안내 보기 →</Link></section></div></>;
 const kind=section as SupportKind,raw=await searchParams,q=typeof raw.q==='string'?raw.q.slice(0,100):'',category=typeof raw.category==='string'?raw.category:'전체';const {entries,state,source}=await publicSupport(kind),rows=selectEntries(entries,kind,q,category),result=paginate(rows,raw.page,kind==='notices'?5:10);const categories=kind==='faq'?['마케팅','교육','자료·문의']:kind==='resources'?['마케팅','SV·교육','운영 양식']:[];const query={...(q?{q}:{}),...(category!=='전체'?{category}:{}),...(result.page>1?{page:String(result.page)}:{})};return <><SupportHero title={title} description={descriptions[kind]}/><div className={s.container}><SupportNavigation/><section className={s.section} data-content-source={source}><Search kind={kind} q={q} category={category}/>{categories.length>0&&<Filters kind={kind} categories={categories} q={q} selected={category}/>}{state==='ready'&&<p className={s.lead}>{rows.length}개의 {kind==='faq'?'질문':kind==='resources'?'자료':'공지'}</p>}{rows.length?(kind==='faq'?<div className={s.faq}>{result.rows.map(e=><details key={e.id}><summary>{e.title}</summary><p>{e.body}</p></details>)}</div>:kind==='notices'?<Notices entries={result.rows} query={query}/>:<ResourceCards entries={result.rows} query={query} heading={2}/>):state!=='ready'?<Empty state={state} kind={kind}/>:q||category!=='전체'?<p className={s.empty}>검색 결과가 없습니다.</p>:<Empty state={state} kind={kind}/>}<Pager kind={kind} page={result.page} pages={result.pages} q={q} category={category}/></section><Consultation/></div></>}
